### ISSUE TITLE
Incorrect oAuth Redirect URI

### ISSUE THREAD

**Issue by jeremywillans** [achhabra2/inquire#6]
I have deployed the Docker Image for testing however the Redirect URI listed in the README is incorrect.

The OAuth Authorization URL is using https://<fqdn>/auth/ciscospark/callback

**Comment by achhabra2** [comment]
Fixed in this commit: 
https://github.com/achhabra2/inquire/commit/cd716ce297197562479db4e875d7c41bf5c4fbf8#diff-04c6e90faac2675aa89e2176d2eec7d8
